/**
 * Reports what `public/assets/` is costing and what of it the app never loads.
 *
 *   node scripts/asset-report.mjs                # summary
 *   node scripts/asset-report.mjs --verbose      # every unreferenced file
 *   node scripts/asset-report.mjs --tier stem    # also list weakly-referenced files
 *   node scripts/asset-report.mjs --emit-prune   # write scripts/prune-assets.sh
 *
 * Read-only. `--emit-prune` writes a shell script of `git rm` commands for you
 * to review and run yourself — nothing here deletes anything.
 */

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import {
  buildCorpus,
  listAssets,
  classify,
  formatBytes,
} from "./lib/assetRefs.mjs";

const ASSET_DIR = "public/assets";
const args = process.argv.slice(2);
const verbose = args.includes("--verbose");
const emitPrune = args.includes("--emit-prune");
const tierArg = args[args.indexOf("--tier") + 1];
const listTier = args.includes("--tier") ? tierArg : null;

const corpus = buildCorpus();
const files = listAssets(ASSET_DIR);

const byTier = new Map();
let total = 0;
for (const file of files) {
  const tier = classify(file.rel, corpus);
  total += file.size;
  if (!byTier.has(tier)) byTier.set(tier, []);
  byTier.get(tier).push(file);
}

const sum = (list) => list.reduce((acc, f) => acc + f.size, 0);
const unreferenced = byTier.get("none") ?? [];

console.log(`\n${ASSET_DIR}: ${files.length} files, ${formatBytes(total)}\n`);
console.log("Reachability from src/:");
for (const tier of ["path", "template", "filename", "stem", "none"]) {
  const list = byTier.get(tier) ?? [];
  if (!list.length) continue;
  const label = {
    path: "literal path in source",
    template: "built by a loop template",
    filename: "filename in a config array",
    stem: "stem match only (weak — verify before deleting)",
    none: "NO reference found",
  }[tier];
  console.log(
    `  ${String(list.length).padStart(4)} files  ${formatBytes(sum(list)).padStart(9)}  ${label}`,
  );
}

// ── Unreferenced, grouped by directory ──────────────────────────────────────
if (unreferenced.length) {
  const byDir = new Map();
  for (const file of unreferenced) {
    const dir = path.dirname(file.rel);
    if (!byDir.has(dir)) byDir.set(dir, []);
    byDir.get(dir).push(file);
  }
  console.log(`\nUnreferenced by directory (${formatBytes(sum(unreferenced))} total):`);
  for (const [dir, list] of [...byDir].sort((a, b) => sum(b[1]) - sum(a[1]))) {
    console.log(
      `  ${formatBytes(sum(list)).padStart(9)}  ${String(list.length).padStart(3)} files  ${dir}`,
    );
    if (verbose) {
      for (const file of list.sort((a, b) => b.size - a.size)) {
        console.log(`             ${formatBytes(file.size).padStart(9)}  ${file.rel}`);
      }
    }
  }
}

if (listTier) {
  const list = byTier.get(listTier) ?? [];
  console.log(`\nFiles in tier "${listTier}" (${formatBytes(sum(list))}):`);
  for (const file of list.sort((a, b) => b.size - a.size)) {
    console.log(`  ${formatBytes(file.size).padStart(9)}  ${file.rel}`);
  }
}

// ── Byte-identical duplicates ───────────────────────────────────────────────
const byHash = new Map();
for (const file of files) {
  if (file.size < 64 * 1024) continue; // ignore trivia
  const hash = crypto
    .createHash("md5")
    .update(fs.readFileSync(file.abs))
    .digest("hex");
  if (!byHash.has(hash)) byHash.set(hash, []);
  byHash.get(hash).push(file);
}
const dupes = [...byHash.values()].filter((list) => list.length > 1);
if (dupes.length) {
  const wasted = dupes.reduce(
    (acc, list) => acc + list[0].size * (list.length - 1),
    0,
  );
  console.log(`\nByte-identical duplicates (${formatBytes(wasted)} wasted):`);
  for (const list of dupes.sort((a, b) => b[0].size - a[0].size)) {
    console.log(`  ${formatBytes(list[0].size).padStart(9)} × ${list.length}`);
    for (const file of list) console.log(`             ${file.rel}`);
  }
}

// ── Optional prune script ───────────────────────────────────────────────────
if (emitPrune) {
  const target = "scripts/prune-assets.sh";
  const lines = [
    "#!/usr/bin/env bash",
    "# Generated by scripts/asset-report.mjs — REVIEW BEFORE RUNNING.",
    "# Only files with no reference of any kind found in src/ are listed.",
    "# Everything here is recoverable from git history after committing.",
    "set -euo pipefail",
    "cd \"$(dirname \"$0\")/..\"",
    "",
    ...unreferenced
      .sort((a, b) => b.size - a.size)
      .map((f) => `git rm --quiet "${ASSET_DIR}/${f.rel}"  # ${formatBytes(f.size)}`),
    "",
    `echo "Pruned ${unreferenced.length} files (${formatBytes(sum(unreferenced))})."`,
  ];
  fs.writeFileSync(target, lines.join("\n") + "\n", { mode: 0o755 });
  console.log(`\nWrote ${target} (${unreferenced.length} deletions). Review it before running.`);
}

console.log("");
